name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install tooling
        run: pip install pyyaml
      - name: Repo check
        run: make check

  package-tests:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [hive-metastore]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install tooling
        run: pip install pyyaml
      - name: Run tests
        run: ./scripts/package.py test ${{ matrix.package }}
