name: Hive Metastore E2E

on:
  push:
    branches: [main]
    paths:
      - 'containers/hive-metastore/**'
      - 'scripts/**'
      - '.github/workflows/hive-metastore-e2e.yml'
  pull_request:
    paths:
      - 'containers/hive-metastore/**'
      - 'scripts/**'
      - '.github/workflows/hive-metastore-e2e.yml'
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Execute Hive Metastore e2e pipeline
        run: containers/hive-metastore/tests/e2e.sh
        shell: bash
